### ISSUE TITLE
Inaccurate Alumni Count

### ISSUE THREAD

**Issue by preete126** [sirlawglobal/OSAAGOS-API-Alumni-Website#6]
The Alumni count is not being returned accurately. The system currently shows a count of 0, whereas we have more than that already in the database. This discrepancy needs to be investigated and resolved to ensure accurate data representation.

**Comment by sirlawglobal** [comment]
which other properties do you to be contained in the response?

**Comment by sirlawglobal** [comment]
fix ...... kindly confirm and close this



{
    "totalAlumni": 6,
    "totalEvents": 3,
    "totalNews": 2,
    "totalMedia": 1
} ................
